set FILE=BOOTROM

x6809 %FILE%.src,%FILE%.s,%FILE%.lst,%FILE%.crf,%FILE%.map /DIPLENT=768
MOT2BIN %FILE%.S %FILE%.BIN
BINCUT %FILE%.BIN BOOT_DOS.ROM FE00 FFFF

x6809 %FILE%.src,%FILE%.s,%FILE%.lst,%FILE%.crf,%FILE%.map /DIPLENT=256
MOT2BIN %FILE%.S %FILE%.BIN
BINCUT %FILE%.BIN BOOT_BAS.ROM FE00 FFFF

SEVEN2AV
